import React from 'react'
import Fade from 'react-reveal/Fade';

class Symmetric extends React.Component  {
  render() {
  return (
    <div className='symmetric'>
        <Fade bottom>
      <h1>
      <Fade left cascade>
        1. Symmetric Encryption
      </Fade>
      </h1>
      <p>Symmetric encryption, also known as secret-key encryption or conventional encryption, is a type of encryption where the same key is used for both the encryption and decryption of data. In other words, the sender and the recipient of the encrypted data share a common secret key. This key is kept confidential and must be known only to the parties that need to encrypt and decrypt the information.</p>
        <ol>
            <span>Here's how symmetric encryption works:</span>

            <li><span className='sub-heading mt-2'>Key Generation:</span> A secret key is generated by one party (typically the sender) or is securely exchanged between the sender and recipient through a trusted channel. This key is a long string of bits.</li>

            <li><span className='sub-heading'>Encryption:</span> The sender uses the secret key and an encryption algorithm (e.g., AES, DES) to transform plaintext data (the original, readable data) into ciphertext (encrypted data). The ciphertext is essentially a scrambled version of the plaintext and appears as random data.</li>

            <li><span className='sub-heading'>Transmission:</span> The ciphertext can be safely transmitted over insecure channels (such as the internet) because it's computationally infeasible to reverse the encryption process and derive the plaintext without the secret key.</li>

            <li><span className='sub-heading'>Decryption:</span> The recipient, who possesses the same secret key, uses it along with the decryption algorithm to reverse the encryption process. This converts the ciphertext back into the original plaintext.</li>
        </ol>
        <ul>
            <span>Key points to note about symmetric encryption:</span>

            <li className='mt-2'> Symmetric encryption is generally faster and more efficient than asymmetric encryption, making it suitable for encrypting large amounts of data.</li>

            <li> The primary challenge in symmetric encryption is securely sharing the secret key between the sender and recipient. If an attacker gains access to the key, they can decrypt the ciphertext and access the plaintext.</li>

            <li> Symmetric encryption is often used for securing data at rest (data stored on a hard drive or in a database), securing data in transit (data sent over a network), and for encrypting files and messages.</li>

            <li> While symmetric encryption is fast and efficient, it requires a secure key distribution mechanism to ensure that the shared secret key is kept confidential and protected from unauthorized access.</li>

            <li> Common symmetric encryption algorithms include AES (Advanced Encryption Standard), DES (Data Encryption Standard), and 3DES (Triple DES). AES, in particular, is widely used and considered highly secure when used with strong keys and appropriate modes of operation.</li>
        </ul>

        <div className="cards container bg-black">
            <div className="maincontainer">
                <div className="back">
                    <h2>Stream Ciphers</h2>
                    <p>
                        Stream ciphers encrypt data one bit or byte at a time, making them suitable for real-time communication. RC4 and ChaCha20 are examples of stream ciphers.
                    </p>
                </div>
                <div className="front">
                    <div className="image">
                        <h2>Stream Ciphers</h2>
                    </div>
                </div>
            </div>

            <div className="maincontainer">
                <div className="back">
                    <h2>Block Ciphers</h2>
                    <p>
                        These encrypt data in fixed-size blocks, typically 128 or 256 bits at a time. Common block ciphers include AES (Advanced Encryption Standard), DES (Data Encryption Standard), and 3DES (Triple DES).
                    </p>
                </div>
                <div className="front">
                    <div className="image d-flex align-items-center justify-content-center">
                        <h2>Block Ciphers</h2>
                    </div>
                </div>
            </div>
        </div>
        </Fade>
    </div>
  )
  }
}

export default Symmetric
